In [ ]:
#1


In [ ]:
#2

In [ ]:
#3

In [ ]:
#4

In [ ]:
#5 
# S.Geometrica

# 8528=a1*r**(5-1)
# 1066=a1*r**1

#Los terminos se dividen

# 8=r**3

#EXTRAER RAIZ

# 2=r

#Reemplazamos en 1066=a1*r**1

# 1066= a1 * 2 ** 1
# 1066= a1 * 2
# 1066 / 2 = a1
# 533 = a1

#an = 533 * 2 **(n-1)
print(533*2**(9-1))

In [ ]:
#6
n = 0
termino = 0
valorfinal = 34112
dif = valorfinal - termino
while dif > 0:
    n = n + 1
    termino = 533 *2**(n-1)
    dif  = valorfinal - termino
print(f'Mes numero: {n}')

In [ ]:
#7
print("""
Sucesion Aritmetica

1396000 = a1 + d*(12-1)
1108000 = a1 + d*(4-1)

1396000 = a1 + 11d
1108000 = a1 + 3d

Los terminos se restan

288000=8d
288000/8=d
36000=d

Reemplazamos 1108000=a1+3d

1108000=a1+3*36000
1108000=a1+108000
1108000-108000=a1
1000000=a1

an=1000000+36000*(n-1)

""")

print(1000000+36000*(24-1))

In [1]:
#8
import numpy as np

T = np.array([[300, 272, 240],
              [260, 180, 324]])

U = np.array([[1200, 1250],
              [1100, 1400],
              [1350, 1200]])

V = T.dot(U)

print(f'V=\n{V}')

V=
[[ 983200 1043800]
 [ 947400  965800]]


In [3]:
#12

S=np.array([[360, 280, 150, 420],
            [450, 370, 210, 130],
            [240, 260, 320, 340]])

C=np.array([[130, 310, 230, 280],
            [270, 240, 520, 370],
            [190, 290, 460, 410]])

T=0.8*S+1.1*C
print(f'T=\n{T}')


T=
[[431. 565. 373. 644.]
 [657. 560. 740. 511.]
 [401. 527. 762. 723.]]


In [4]:
A=np.fromfunction(lambda i,j: 2*(i+1)+3*(j+1), (3,3))

B=np.fromfunction(lambda i,j: 10*(i+1)*(j+1), (3,3))

C=A.dot(B)
print(C)

[[ 540. 1080. 1620.]
 [ 660. 1320. 1980.]
 [ 780. 1560. 2340.]]


In [ ]:
#14
N=np.array([[2, 1],
            [3, -2]])

M=np.array([[10],
            [8]])

NI=np.linalg.inv(N)

Sol=NI.dot(M)

print(Sol)

[[4.]
 [2.]]


In [11]:
#16
A=np.array([[2, 3],
            [1, 2]])

AI=np.linalg.inv(A)
print(AI)
#17
AT=A.T
print('')
print(AT)
#19
print('')
T=A+AT
print(T)

[[ 2. -3.]
 [-1.  2.]]

[[2 1]
 [3 2]]

[[4 4]
 [4 4]]


In [ ]:
#20
